### PR TITLE
Added first xpub in Bitcoin Fun section

### PR DESCRIPTION
**Pull request by Thierry61**

### CODE REVIEW

**Comment by Thierry61** [comment]
Hi @prusnak. Sorry to disturb you, but I would like to discuss with you about this PR.

It adds the first example of a leaked xpub in Bitcoin Fun section of BTC RPC Explorer (xpubs were allowed recently in this section). It is a perfect example because it shows how things can go wrong when a xpub key is leaked together with a derived private key. But the problem with the [embedded link](http://www.ztohoven.com/?lang=en) is the criticism of your action at that time, and so I need your approval before I submit this PR.

**Comment by prusnak** [comment]
@Thierry61 I prefer this not to be added. The blogpost does not explain truthfully what has happened.

**Comment by Thierry61** [comment]
No problem, I will close the PR.

Note that I am interested if you happen to know another interesting example of a leaked xpub key (with a non-controversial link!)

**Comment by arashaliloo** [comment]
Hello. If xpub zpub ypub wallet has Bitcoin, you can extract it. I will extract the private key of the same wallet. And I will become a partner.

**Pull request closed without merging**
