### PR TITLE
A bunch of stuff

### PR DESCRIPTION
**Pull request by shesek**
This is some stuff I've been working on. I'm posting this here for discussion, if you find any of the changes acceptable, please let me know and I'll make separate PRs with just the wanted bits.

Main changes:

- Read configuration options from environment variables (this is also opened as #88)

- Support bitcoind cookie file, reads `~/.bitcoin/.cookie` by default if it exists (if you're on mainnet with standard rpc ports and the datadir is `~/.bitcoin`, the rpc connection should Just Work :tm: out-of-the-box)

- Added an `btc-rpc-explorer` CLI executable. After installing the package with `npm install -g`, the server can be started like so:

    ```bash
    $ btc-rpc-explorer --port 8080 --bitcoind-port 18443 --bitcoind-cookie ~/.bitcoin/regtest/.cookie
    ````

- Added optional password protection for the web interface, configurable with `--login <password>` or `BTCEXP_LOGIN`

- Added [CSRF](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)) protection

- Added `--no-rates` to disable communication with the exchange rate API providers

With these changes in place, assuming you're with standard bitcoind mainnet configs, it is sufficient to run `npx janoside/btc-rpc-explorer` to get btc-rpc-explorer started!

### CODE REVIEW

**Comment by zciendor** [comment]
It seems like the `--no-rates` option only hides the exchange rate from being shown in the UI, but it still tries to communicate with the API servers. We have all Clearnet communication blocked on the zHIVErbox, that's why we see these errors in the log:

```
Running RPC Explorer for Bitcoin
Connecting via RPC to node at 127.0.0.1:8332
Connected via RPC to node.
Error:
{ Error: connect ECONNREFUSED 151.101.12.133:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '151.101.12.133',
  port: 443 }
Response:
undefined
Error:
{ Error: connect ECONNREFUSED 151.101.12.133:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '151.101.12.133',
  port: 443 }
Response:
undefined
```

**Comment by zciendor** [comment]
@shesek: Thanks to your consolidation work we deleted our fork and switched to the upstream repository for zHIVErbox: https://github.com/zhiverbox/armbian-userpatches/commit/d39c4dbbfd034fd0600f56726bda459f28f2449e

**Comment by shesek** [comment]
The line here is supposed to prevent the requests from going out:

**Comment by shesek** [comment]
The line here is supposed to prevent the requests from going out: https://github.com/janoside/btc-rpc-explorer/pull/89/commits/bfcbcd07a463c8eb782540e81d34226ffd8bca3a#diff-1439419fefbc1758ab0d743f2ec998ebR279

This seems to work for me. Can you try with `BTCEXP_NO_RATES=1` instead of the `--no-rates` CLI arg and see if that works?

**Comment by zciendor** [comment]
Ah sorry, the IP address `151.101.36.133` in the error messages seems to be `GitHub` and not an exchange API. So `btc-rpc-explorer` is trying to access some GitHub resources on startup, which is causing these errors on zHIVErbox.

**Comment by shesek** [comment]
Oh, I see. It's fetching the list of pools and their identifies from github. See here:

- https://github.com/janoside/btc-rpc-explorer/blob/16e387be8989aa64e24b40711b7239c24470ae7b/app/coins/btc.js#L61-L64

- https://github.com/janoside/btc-rpc-explorer/blob/16e387be8989aa64e24b40711b7239c24470ae7b/app.js#L301

I'll look into making that optional too. Are there any other requests being sent out except this?

**Comment by shesek** [comment]
@janoside Would it make sense to bundle the `pools.json` files into the package and update them occasionally instead of fetching them dynamically? We can have an `npm run update-pools` script so users could manually update the list if they wanted to, and add this script as a `prepublish` build step so it'll get updated with every new release.

**Comment by janoside** [comment]
@shesek Hmmm, I'm not sure. My first reaction was: "Yes, packaging sounds fine, and useful toward the goal here of restricting outbound traffic". After a little more thought I started to question the merits of this pursuit.

@zciendor Could you explain a little more about what you'd like to see here? Are these errors you're seeing show-stoppers? And if so, how far does the issue extend? For example, the site is dynamically pulling in many CDN-served frontend resources. Are these also a problem?

I want to avoid going overboard for the wrong reasons. If the goal is to clean up some errors from a log that are to be expected in a particular, restricted environment, I'm not liking the trade-offs. If the goal is a super privacy-conscious, self-contained project I can see the appeal, but the work will probably be more involved since that hasn't been a guiding design principle from the start.

**Comment by zciendor** [comment]
> Are these errors you're seeing show-stoppers?

No

> the site is dynamically pulling in many CDN-served frontend resources. Are these also a problem?

No, frontend resources are not pulled by the zHIVErbox anyway, they are pulled by the browser - which runs on the user's desktop machine and not on the zHIVErbox (which is a headless system).

There's no immediate action needed. zHIVErbox is blocking these requests anyway, so it's IP address is not leaked to a network observer/adversary. 
However, hard-coupling the btc-rpc-explorer nodejs application to a centralized service like GitHub might not be the best design decision in the era of decentralized applications. Here are our thoughts with descending preference:

1. We would side with @shesek and bundle pools.json along with the package.
2. Alternatively, if this file should really be fetched dynamically (because it changes often) a decentralized location like IPFS (IPNS path) might be preferable over GitHub!?
3. Or, if btc-rpc-explorer would at least allow a SOCKS5 proxy to be configured for any outbound requests we could proxy those requests over Tor.

**Comment by janoside** [comment]
@zciendor Thanks for the reply explaining your needs and describing your preferences. I can get on board pulling these json configs into the project. I agree downloading from GitHub is lame here - this feature was intended to be a user-configurable thing but wasn't exposed as such. I created Issue #100 to track this.

**Comment by shesek** [comment]
> For example, the site is dynamically pulling in many CDN-served frontend resources. ... If the goal is a super privacy-conscious, self-contained project I can see the appeal, but the work will probably be more involved since that hasn't been a guiding design principle from the start.

Bundling the CDN files into the package is actually something that I've been meaning to look into, maybe as an optional flag. Other than this and the pools, are there any other changes required to make btc-rpc-explorer self-contained?

I think the benefits of a self-contained package are quite significant:

1. This means the explorer will work without dependencies on internet resources and internet access, which makes this more portable and easier to run behind LANs and firewalls. 

2. This also has privacy benefits, especially because of the `Referrer` header which leaks the urls of viewed pages (including the txid/blockhash the user was browsing) to the CDN providers.

3. This also has security benefits, because external `<script>` tags with no `integrity` attribute (or all `<script>` tags on browsers that don't support `integrity`) can be modified by the CDN provider to return a different JavaScript code, which would execute inside the btc-rpc-explorer origin sandbox (with access to localStorage, cookies, ability to send XHR requests, etc). From what I can tell, there's currently one `<script>` tag with no `integrity`, which also points to a plain http url with no tls encryption.

> Or, if btc-rpc-explorer would at least allow a SOCKS5 proxy to be configured for any outbound requests we could proxy those requests over Tor.

I think this is a good option for requests sent out from the btc-rpc-explorer server side. At the very least, sending out periodic requests to bitcoin rates/pools exposes the fact that you're running a bitcoin-related service, which some users might prefer to hide. (the [instructions for the bitcoin full node workshop](https://github.com/bitembassy/home-node/) we're organizing at the TLV bitcoin embassy sets up Bitcoin Core's outgoing traffic to route through Tor [for this reason (among others)](https://imgur.com/a/FWnYyZx))

**Comment by janoside** [comment]
Good description of the benefits. I created #101 to track this and we can continue discussion there as needed. At the moment I can just think of those 2 items: internalizing frontend resources and internalizing mining pool identification configs. We can address others as we discover them.

**Pull request merged**
