### PR TITLE
Don't strip trailing zeros from values

### LINKED ISSUE #500: Display numbers in a sat compatible standard.
The idea is to make it easy for people to read the amounts from the right side.

Currently on RPC-Explorer
0.000123 can be confused with 0.0000123

0.0001230 format would solve this.

I've noticed that decimals are being trimmed.
image

### PR DESCRIPTION
**Pull request by ExperiBass**
Closes #500.

### CODE REVIEW

**Comment by janoside** [comment]
Thanks for this. Merged and tweaked. See https://github.com/janoside/btc-rpc-explorer/commit/2584d870326e77a06305b8a3b407c054f611ce70

**Review by Giorgikobalia — COMMENTED** [review]
leave

**Review by Giorgikobalia — COMMENTED** [review]
Approval

**Review by Giorgikobalia — COMMENTED** [review]
leave

**Pull request merged**
