### PR TITLE
Store params in environment variables and avoid file changes

### PR DESCRIPTION
**Pull request by diegogurpegui**
Added the "dotenv" module to handle the env variables merged with the .env file.
Reasons:
1. config files (like `credentials.js`) are committed and should not be changed locally, instead change the server environment variables
2. sensitive information should not be committed, and it's a good practice to keep them in the env so they are server specific

Also adjusted the README file to mention the environment variables.

### CODE REVIEW

**Comment by zciendor** [comment]
I just noticed I made a similar/related pull request: https://github.com/janoside/btc-rpc-explorer/pull/61

I fixed the implementation of the `RPC_` environment variables, which were supposed to be used to override `credentials.js` config (I guess).
I also implemented support for [RPC cookie authentication](https://bitcoin.org/en/release/v0.12.0#rpc-random-cookie-rpc-authentication), so it's no longer neccessary to modify the default bitcoin.conf to make `btc-rpc-explorer` work.

**Comment by diegogurpegui** [comment]
Your comment made me realize of that piece of code in the `app.js` file, which I overlooked.
I will adjust it to avoid that unnecessary if. The RPC config should always be taken from the config file. In fact, to the rest of the application, the fact that the parameters come from env should be completely transparent.

Thanks!

**Comment by diegogurpegui** [comment]
Done! updated.

I still have doubts about the names of the new env variables I picked. Should we use the "BTCEXP_" prefix? Are these variables really going to be used as OS variables along with other services (an scenario where it's worth differentiating)? or in those cases the admins will just use the ".env" file?
Thoughts?

**Comment by zciendor** [comment]
> you didn't include the "pick from env" logic into the config files

Yes, I saw your PR only **after** I pushed mine already. I think I'll redo the `RPC Cookie Authentication` logic based on your changes when you are done.

> Are these variables really going to be used as OS variables along with other services

I'm not sure. For our [zHIVErbox](https://github.com/zhiverbox/armbian-userpatches) we'll use these variables in a wrapper shell script to easily switch between Bitcoin `mainnet` and `testnet` which looks like:

```
#!/bin/bash
...
NETWORK=${1:-mainnet}

echo "Starting BTC RPC Explorer for '$NETWORK'";
case $NETWORK in
    mainnet)
        bitcoind_config=/etc/bitcoin/bitcoin.conf;
        bitcoind_default_rpcport=8332;;
    testnet)
        bitcoind_config=/etc/bitcoin/test_bitcoin.conf;
        bitcoind_default_rpcport=18332;;
    *) echo "Unsupported network '$NETWORK'. Please use 'mainnet' or 'testnet'" && exit 1;;
esac

cookiefile=$(cat $bitcoind_config | grep 'rpccookiefile=' | awk -F'=' '{print $2}')/authcookie
...
RPC_HOST="localhost" RPC_PORT="$bitcoind_default_rpcport" RPC_COOKIEFILE="$cookiefile" yarn start
```

All of this could be implemented in `app.js` or `config.js` directly of course and maybe in the future `btc-rpc-explorer` allows switching between `mainnet` and `testnet` in the web UI. But that doesn't mean there won't be others who still need the case to override config files via env variables...

**Comment by janoside** [comment]
@diegogurpegui @zciendor I like what you're both doing here, and I'll defer to your judgement and experience about the final approach. How are you both feeling about the two pull requests? Are we consolidating on this one (#56)?

**Comment by diegogurpegui** [comment]
Thanks for the feedback @janoside !
In terms on how to handle this, I think that given the current situation I would keep this #56 focused on the env variables only, and keep #61 focused on the cookie authentication (which @zciendor seems to know about and I didn't take a good look at it yet). That way we have both PR separated in term of concerns. How does that sound? @zciendor how do you feel about changing the title of the PR?

Regarding my earlier comment about the env variables name. I think it would be better now to have them all start with "BTCEXP_" (or any other prefix you like) to keep them isolated from any other environment variable and avoid conflicts in the deployment machines. After this PR, the next step will be to migrate as much parameters or configurations to env variables.

**Comment by shesek** [comment]
Configuring via environment variables and cookie file support would be awesome. What's missing to make that happen? If I make a new PR on top of master, would you consider accepting it?

**Comment by janoside** [comment]
@shesek Yes. This honestly just fell off my radar. I'll be happy to consider a new PR on master.

**Comment by shesek** [comment]
Awesome! Will get on it. Do you prefer the environment variables with the `BTCEXP_` or without it?

**Comment by diegogurpegui** [comment]
If you think this PR is something missing, feel free to work on top of it. Otherwise, I think we could merge it.

**Comment by janoside** [comment]
Changes made in https://github.com/janoside/btc-rpc-explorer/pull/88 - thanks again for all the input on this.

**Pull request closed without merging**
