### PR TITLE
Update to use bitcoin-core instead of bitcoin node package

### PR DESCRIPTION
**Pull request by nkostoulas**
Update explorer to use the new bitcoin-core npm package instead of the deprecated bitcoin one

### CODE REVIEW

**Comment by janoside** [comment]
I like the idea here. I hadn't noticed that the "bitcoin" npm package was deprecated so thanks for the heads up. Two points on your PR:

1. I merged your first commit locally and several pages were broken. I see there's a new commit now. What's the status on your changes with the second commit?
2. Can you re-work to cut down on whitespace only changes? I want the diff to be minimal and all the whitespace only changes are making that rough.

**Comment by nkostoulas** [comment]
Which pages are broken? I'm just testing with bitcoind on regtest and don't see any problems (for the first commit that is).

**Comment by janoside** [comment]
From the homepage I'm unable to navigate to "/block-height/517875". There seems to be a problem with a "getRawTransactions" batch not completing properly.

It also looks like you might have some uncommitted code pertaining to RPC credentials? The change [here](https://github.com/janoside/btc-rpc-explorer/pull/24/commits/5bda204adda430829844dff6882970ea44f902da#diff-0364f57fbff2fabbe941ed20c328ef1aR64) is referring to a "host" variable that doesn't exist.

**Comment by nkostoulas** [comment]
Ah okay the first was introduced by the api change, the recursion in getrawtransactions was not working properly. I've fixed this in the second commit. 

As for the second I see what you mean. I was using the connect page and didn't spot this.

Should I redo this to avoid the whitespace change commits?

**Comment by janoside** [comment]
Yea, if you can redo that'd be great.

**Pull request closed without merging**
